---
title: "EDS 215 Day 3 Notes"
author: "Scout Leonard"
date: "9/1/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### SQL

To run SQL in the command line, run `sqlite3`

To quit SQL, run `.q`. 

*SQL is a workflow. Rarely do you work with databases in the database.*

**NOTE:** an **alias** in Bash lets you shortcut a command as some personalized command! 

- `--` comments out the code
- verbose language! 
- "structured query language": originally made for ordinary people to communicate with databases
  - has since become a programming language, and lost this definition! 
- always starts with a **VERB**
  - then an **object**, want to want to apply the verb to 
  - then what you're taking the data form
  - then a logical expression 
- *Philosophy* SQL is a symbolic language, whereas R is imperative. You can find things in databases, but you can't assign variables or tell databases to do specific things. 
- case insensitive! 

#### Databases
- *Everything in a database is a table.* You can save items of interest in SQL as a database.
- order of observations doesn't matter
- order of columns/variables doesn't matter
- "relational" databases refers to the fact that the observations are not related to each other, but grouped 
- R doesn't know about what's going on inside databases. When you have a database, it's added to the whole database, but it won't show up in the environment, becuase R only knows about DB. Only SQL knows about the new tables you make. 
- you can open and write into the database through the terminal and through R Studio using SQ Lite 3. 

- **null**: it's legitimate to have an observation with an unknown value. It's treated as a "known unknown." It represents a *possible* value, where we don't know what it is. 

#### Aggregations

Aggregations for on a single column value and *sort out the nulls.* (for example, if taking the mean of 9 rows with one null value, the sum will be divided by 8, not 9, discounting the na value).

- `count()` counts the number of rows returned. 
- if you run `.mode box` you can return table data in actual tables!!
- **Group By** 

### Day 4 Notes

#### Combining Data

- **Joins** match two tables based on matching values in columns. 
- Building a join is to combine data into tables you can ask questions of 
  - If you want to ask questions of multiple tables, you have to join them to ask a question of them .
  - subsets rows based on columns being equal 
- "Views are a huge win because you can use them as a form of documentation." 

#### Data Hygiene 

- Databases can't function if we can't tell one row from another, so every row has an identifier. In SQL, it's a **Row ID**. This means that even if row's aren't unique, SQL can tell them apart. 
  - They are sequentially assigned. 
  - This Row ID is otherwise totally useless
  - don't use it lol
  - This identifier acts as a **primary key** for the row. 
  - **Referential integrity** the integrity of keys is preserved
    if you call a column a key, the integrity of the individual keys are preserved 
    - Combining datasets based on a common variable is a way of setting foreign **key/primary key relationships** 
    
**Atomic values** can be subject to standard operators. Make sure the values in a row are each their own observation. 

#### Creating and Modifying Data

- `CREATE TABLE` : creates a new table. it's arguments are the names and types of the tables columns

  - When you create a table, you can't create another table on top of it in the same name. You have to drop it first. 

*Examples:*
  - `CREATE TABLE Person(id text, personal test, family text);`
    `CREATE TABLE Site (name text, lat real, long real);`
    `CREATE TABLE Visited(id integer,site text,dated integer);`
    
    - `CREATE TABLE Survey(`
      `taken   integer not null,` -- where reading taken
      `person  text,`             -- may not know who took it
      `quant   text not null,`    -- the quantity measured
      `reading real not null,`    -- the actual reading
      `primary key(taken, quant),`
      ` foreign key(taken) references Visited(id),`
      `foreign key(person) references Person(id)`
      `);`
      
- `DROP TABLE` : gets rid of one of our tables. be careful using this! 
- creating and dropping tables is easier in the command line 
- **Data Types**
  - *INTEGER*: a signed integer
  - *REAL*: a floating point number
  - *TEXT* : a character string
  - *BLOB*: a "binary large object", such as an image  

- `INSERT INTO table` adds observations to your table  
*Example*: 

  - `INSERT INTO Site (name, lat, long) VALUES ('DR-1', -49.85, -128.57);`
    `INSERT INTO Site (name, lat, long) VALUES ('DR-3', -47.15, -126.72);`
    `INSERT INTO Site (name, lat, long) VALUES ('MSK-4', -48.87, -123.40);`

- Opposite of a **select statement** is a **remove statement**, which removes rows from your df. 
*Examples*:

  - `delete from foo where bar = 4;`
    - `INSERT INTO foo (bar, baz) VALUES (4, 42);` adds the value back! 
    - `SELECT * from foo;` lets you check! 
  - `update foo set baz=500 where baz=100;` changes an observation
    - `select * from foo;` allows you to check!
    
    
If you have lots of manipulation you are doing to a database, put it in a file (like Text Editor!). 

