---
title: "Databases and SQL queries"
output:
  html_document:
    df_print: paged
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

connect Rmd SQL chunk to SQLite database

```{r}
library(DBI)
# this line connects to a database, saving a reference to the database as the variable "db"
db <- dbConnect(RSQLite::SQLite(), dbname = "survey.db")
```

## 1. [Selecting Data](https://swcarpentry.github.io/sql-novice-survey/01-select/index.html)

```{bash}

#bash in the header means this code is sent to bash through Rmd, then runs the line, then closes bash. This means context doesn't carry over from one block to the next. This means you can't have the same bash script in multiple blocks! 

echo '.tables' | sqlite3 survey.db
```
```{sql connection=db}
-- set up to use the standard sql syntax (capitalize all the words, although sql is case insensitive)
-- space is also not important
-- operation is SELECT
-- following elements defines variables of interest, where * means all the columns
SELECT name AS tables FROM sqlite_master WHERE type = 'table'

-- this is how you comment out sql
```

```{bash}
echo '.schema' | sqlite3 survey.db
```
```{sql connection=db}
SELECT sql AS schema FROM sqlite_master
```

```{sql connection=db}
SELECT family, personal FROM Person;
```

```{sql connection=db}
SeLeCt FaMiLy, PeRsOnAl FrOm PeRsOn;
```

```{sql connection=db}
SELECT personal, family FROM Person;
```

```{sql connection=db}
SELECT id, id, id FROM Person;
```

```{sql connection=db}
SELECT * FROM Person;
```

## 2. [Sorting and Removing Duplicates](https://swcarpentry.github.io/sql-novice-survey/02-sort-dup/index.html)

```{sql connection=db}

-- gives every row, and for every row, we select out the column 

SELECT quant FROM Survey;
```

```{sql connection=db}

-- SELECT DISTINCT means only return rows that are unique
SELECT DISTINCT quant FROM Survey;
```

```{sql connection=db}
SELECT DISTINCT taken, quant FROM Survey;
```

```{sql connection=db}

-- selects everything from the Person table, then selects the results by id. 

SELECT * FROM Person ORDER BY id;
```

```{sql connection=db}
SELECT * FROM person ORDER BY id DESC;
```

```{sql connection=db}
SELECT taken, person, quant FROM Survey ORDER BY taken ASC, person DESC;
```

```{sql connection=db}
SELECT DISTINCT quant, person FROM Survey ORDER BY quant ASC;
```

## 3. [Filtering](https://swcarpentry.github.io/sql-novice-survey/03-filter/index.html)

```{sql connection=db}

--return rows that match some argument

SELECT * FROM Visited WHERE site = 'DR-1';
```

```{sql connection=db}
SELECT id FROM Visited WHERE site = 'DR-1';
```

```{sql connection=db}

-- sql treats dates cavalierly. sql doesn't have a date 'type.' 
-- < DATE gives you data from before the date
SELECT * FROM Visited WHERE site = 'DR-1' AND dated < '1930-01-01';
```

```{sql connection=db}
SELECT * FROM Survey WHERE person = 'lake' OR person = 'roe';
```

```{sql connection=db} 

-- test for set membership. possible match to any of the items in '', without having to write a full 'OR' statement. 

SELECT * FROM Survey WHERE person IN ('lake', 'roe');
```

```{sql connection=db}

-- this is a longhand version of teh command above 

SELECT * FROM Survey WHERE person = 'lake' OR person = 'roe';

```


```{sql connection=db}
SELECT * FROM Survey WHERE quant = 'sal' AND person = 'lake' OR person = 'roe';
```

```{sql connection=db}
SELECT * FROM Survey WHERE quant = 'sal' AND (person = 'lake' OR person = 'roe');
```

```{sql connection=db}

-- percent wildcard is analogous to the * wildcard for file expansion 
-- the column site has to have a value that's "like" the expression "DR%", aka starts with "DR...."

SELECT * FROM Visited WHERE site LIKE 'DR%';
```

```{sql connection=db}

SELECT DISTINCT person, quant FROM Survey WHERE person = 'lake' OR person = 'roe';
```

## 4. [Calculating New Values](https://swcarpentry.github.io/sql-novice-survey/04-calc/index.html)

```{sql connection=db}

-- select an arithmetic expression that involves a column
--pulling out the rows where quantity is "rad" and multiplying the values by 1.05

SELECT 1.05 * reading FROM Survey WHERE quant = 'rad';
```

```{sql connection=db}

-- 'AS' renames the column of the new table for us. same function as above, but we've manimulated the column name 

SELECT 1.05 * reading AS adj_reading FROM Survey WHERE quant = 'rad';


```


```{sql connection=db}
SELECT taken, round(5 * (reading - 32) / 9, 2) FROM Survey WHERE quant = 'temp';
```

```{sql connection=db}

-- with the recalculated column renamed "Celisius"

SELECT taken, round(5 * (reading - 32) / 9, 2) as Celsius FROM Survey WHERE quant = 'temp';
```

```{sql connection=db}

-- concatenate observations in 2 columns into a single column 

SELECT personal || ' ' || family FROM Person;
```

```{sql connection=db}

--same command as above without the space!

SELECT personal || "" || family FROM Person;

```


```{sql connection=db}
SELECT * FROM Person WHERE id = 'dyer' UNION SELECT * FROM Person WHERE id = 'roe';
```

```{sql connection=db}
SELECT DISTINCT site FROM Visited;
```

## 5. [Missing Data](https://swcarpentry.github.io/sql-novice-survey/05-null/index.html)

```{sql connection=db}
SELECT * FROM Visited;
```

```{sql connection=db}

-- "create" means "create some structure in the database 
-- Views saves space for speed
-- Creating a new table saves speed for space 

CREATE VIEW Scout_query AS SELECT * FROM Visited WHERE dated < '1930-01-01';
```

```{sql connection=db}
SELECT * FROM Visited WHERE dated >= '1930-01-01';
```

```{sql connection=db}

SELECT * FROM Scout;

```


```{sql connection=db}

-- this fails because null is not a legal value, so you can't compare it. any test involving null can't be tested and has to be false! any logical test you do on null will fail. 

SELECT * FROM Visited WHERE dated = NULL;
```

```{sql connection=db}

-- 
SELECT * FROM Visited WHERE dated != NULL;
```

```{sql connection=db}

-- IS NULL is not a logical test, just a status test, so this works with null values! 

SELECT * FROM Visited WHERE dated IS NULL;
```

```{sql connection=db}
SELECT * FROM Visited WHERE dated IS NOT NULL;
```

```{sql connection=db}
SELECT * FROM Visited WHERE dated IN ('1927-02-08', NULL);
```

## 6. [Aggregation](https://swcarpentry.github.io/sql-novice-survey/06-agg/index.html)

```{sql connection=db}
SELECT dated FROM Visited;
```

```{sql connection=db}
SELECT min(dated) FROM Visited;
```

```{sql connection=db}
SELECT max(dated) FROM Visited;
```

```{sql connection=db}
SELECT avg(reading) FROM Survey WHERE quant = 'sal';
```

```{sql connection=db}

-- count() counts the number of rows returned 

SELECT count(reading) FROM Survey WHERE quant = 'sal';
```
```{sql connection=db}

--if you ask for a non-aggregate value in addition to an aggregate, it will just throw in the last value run, which doesn't have anything to do with the calculated aggregate value is

-- the query that should not be asked! 

SELECT dated, count(site) FROM Visited;

```

```{sql connection=db}

-- we get accurate results when we place aggregate values next to each other. the dated value it lower from an NA observation! 

SELECT count(dated), count(site) FROM Visited;

```

```{sql connection=db}

-- another example of adding aggregate and non aggregate values being Bad queries 

SELECT count(dated), sum(dated), count(site), sum(site) FROM Visited;

```

```{sql connection=db}
SELECT sum(reading) FROM Survey WHERE quant = 'sal';
```

```{sql connection=db}
SELECT min(reading), max(reading) FROM Survey WHERE quant = 'sal' AND reading <= 1.0;
```

```{sql connection=db}
SELECT person, count(*) FROM Survey WHERE quant = 'sal' AND reading <= 1.0;
```

```{sql connection=db}
SELECT person, max(reading), sum(reading) FROM Survey WHERE quant = 'missing';
```

```{sql connection=db}
SELECT min(dated) FROM Visited;
```

```{sql connection=db}
SELECT min(dated) FROM Visited WHERE dated IS NOT NULL;
```

```{sql connection=db}

SELECT person, count(reading), round(avg(reading), 2)
FROM  Survey
WHERE quant = 'rad';
```

```{sql connection=db}
SELECT person, count(reading), round(avg(reading), 2)
FROM  Survey
WHERE quant = 'rad'
AND   person = 'dyer';
```

```{sql connection=db}

-- where clause takes tables and pulls out rows. group by breaks the database into piles and the select aggregates for each pile! 
SELECT   person, count(reading), round(avg(reading), 2)
FROM     Survey
WHERE    quant = 'rad'
GROUP BY person;
```

```{sql connection=db}

-- it is possible to group by null values, becuase they are distinct values in the table 

SELECT   person, quant, count(reading), round(avg(reading), 2)
FROM     Survey
GROUP BY person, quant;
```

```{sql connection=db}

-- table is survey
-- pulling out the rows where person is not null
-- of the rows left, we are grouping them by person and quantity
--that gets returned to the selection process: aggregate over the reading values and give the count and average
--order gives us the observations in alphabetical order by the variable called 

SELECT   person, quant, count(reading), round(avg(reading), 2)
FROM     Survey
WHERE    person IS NOT NULL
GROUP BY person, quant
ORDER BY person, quant;
```

```{sql connection=db}

-- select statement gives us an average of the reading, and then we can use the result to use in other calculations, as demonstrated below

SELECT reading - avg(reading) FROM Survey WHERE quant = 'rad';
```

```{sql connection=db}

-- nested selects include other selects 

SELECT reading - (SELECT avg(reading) FROM Survey WHERE quant = 'rad')
FROM   Survey
WHERE  quant = 'rad'
```

## 7. [Combining Data](https://swcarpentry.github.io/sql-novice-survey/07-join/index.html)

```{sql connection=db}
SELECT * FROM Site JOIN Visited;
```

```{sql connection=db}

-- joining ON says: the only rows I care about are the ones where the name from the name from the site table = the name from the visited table 
-- because we are joining multiple tables, there is the possibility of column names clashing 

SELECT * FROM Site JOIN Visited ON Site.name = Visited.site;
```

```{sql connection=db}

-- same join, but we include when and where each site was visited 

SELECT Site.lat, Site.long, Visited.dated
FROM   Site JOIN Visited
ON     Site.name = Visited.site;
```

```{sql connection=db}

-- looking at two columns and seeing if they're equal 

SELECT Site.lat, Site.long, Visited.dated, Survey.quant, Survey.reading
FROM   Site JOIN Visited JOIN Survey
ON     Site.name = Visited.site
AND    Visited.id = Survey.taken
AND    Visited.dated IS NOT NULL;
```

```{sql connection=db}

-- dataframes come with row ids that you get for free?? if you have duplicate rows and want to tell them apart, you need to make up a column attribute to distinguish them. 

SELECT rowid, * FROM Person;
```

```{sql connection=db}
SELECT Site.name
FROM   Site JOIN Visited
ON     Site.lat <- 49.0
AND    Site.name = Visited.site
AND    Visited.dated >= '1932-01-01';
```

## 11. [Programming with Databases - R](https://swcarpentry.github.io/sql-novice-survey/11-prog-R/index.html)

```{r}
results <- dbGetQuery(db, "SELECT Site.lat, Site.long FROM Site;")
print(results)
```

```{r}
getName <- function(personID) {
  query <- paste0("SELECT personal || ' ' || family FROM Person WHERE id =='",
                  personID, "';")
  return(dbGetQuery(db, query))
}

print(paste("full name for dyer:", getName('dyer')))
```

```{r}
dbListTables(db)
```

```{r}
dbDisconnect(db)
```

